name: ACME Tiny tests

on:
  push:
    branches:
      - main
    paths:
      - "tests/*.py"
      - "acme_tiny_2.py"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    name: Run tests

    strategy:
      matrix:
        include:
          - test-name: ubuntu-22.04-python-3.9
            os: ubuntu-22.04
            python-version: "3.9"

          - test-name: ubuntu-22.04-python-3.10
            os: ubuntu-22.04
            python-version: "3.10"

          - test-name: ubuntu-22.04-python-3.11
            os: ubuntu-22.04
            python-version: "3.11"

          - test-name: ubuntu-24.04-python-3.12
            os: ubuntu-24.04
            python-version: "3.12"

          - test-name: ubuntu-24.04-python-3.13
            os: ubuntu-24.04
            python-version: "3.13"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Setup pebble
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go install github.com/letsencrypt/pebble/...@HEAD
            pebble -h || true

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv venv
          uv sync --frozen

      - name: Run tests
        run: |
          export ACME_TINY_PEBBLE_BIN=$(go env GOPATH)/bin/pebble
          uv run python -m unittest tests
